# encoding: UTF-8
source 'https://rubygems.org'

gem 'rails', '3.2.18'

gem 'mysql2', '~> 0.3.10'
gem 'activerecord', '>= 3.1.2 '

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  #gem 'bootstrap-sass', '~> 3.3.1'
  gem 'bootstrap-sass', '~> 2.2.2.0'

  gem 'coffee-rails', '~> 3.2.1'
  gem 'coffee-script-source'
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  #gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
  gem 'jquery-fileupload-rails'
  gem 'turbo-sprockets-rails3'
  gem 'chosen-rails'
end

group :production, :staging do
  # Use unicorn as the app server
  gem 'unicorn'
  gem 'unicorn-worker-killer'
end

# Deploy with Capistrano
gem 'capistrano', '~> 2.15'

gem 'apartment'
#gem 'rabl'
gem 'execjs'
gem 'therubyracer', '~> 0.12.0'
gem 'activeadmin', '~> 0.6.0'
# gem 'dalli'
gem "cancan"
#gem 'decent_exposure'
gem 'mobile-fu'
# gem 'mobylette'
# gem "paperclip", "~> 3.0"
gem 'magic_encoding'

#======================================
# decorator features
#======================================
gem 'draper'


#======================================
# view features
#======================================
gem 'haml'
gem "haml-rails"
gem 'jquery-rails'
gem 'angularjs-rails'
#gem 'angularjs_scaffold'
gem 'angular-ui-bootstrap-rails'
gem 'angular-rails-templates'

# form
gem 'simple_form'
# simple_form_angula-r0.0.1 何も起きない
# gem 'simple_form_angular'

# multistep form support
gem 'wicked'

# state machine
# redmine 7697 バージョンアップでの問題解決を図るが、バージョン4への移行は手間がかかるので、3の最新にバージョンアップ
gem 'aasm', "~> 3.0"

gem "rails-settings-cached", "0.2.4"
# gem "rails-settings", :git => "git://github.com/100hz/rails-settings.git"
#gem "mongoid", "~> 2.0"
#gem "bson_ext", "~> 1.3"
#gem "mongoid_session_store"
#gem "mongo_store"
# gem 'ransack'
gem 'liquid'
#gem 'panoramic', :git => "ssh://potvalley@potvalley.s-rep.net:11022/home/potvalley/git/panoramic.git", :branch => "coobal"
#gem 'panoramic', :git => "ssh://git.s-rep.net//home/bitnami/git_repos/panoramic.git", :branch => "coobal"
# gem 'unicorn'
# gem 'format_fallback', :git => "https://github.com/cannikin/format_fallback.git"
gem 'bourbon'
gem 'enumerize'
# gem 'enumerated_attribute'
gem 'carrierwave'
gem "rmagick"
#gem 'sanitize'
# seedbankだとapartmentのクライアントのデータベースにうまくseedできない
# その他にも適当なbootstrap gemがないので、デフォルトのseeds.rbを使う
# gem "seedbank"
#gem 'composite_primary_keys'

# gem 'bullet' # N+1 Detection
gem 'ancestry'

gem 'active_attr'

gem 'jp_prefecture', '0.3.2'
# Segmentation faultで終了してしまうので、一旦あきらめる
# gem 'ruby-units', '1.4.2'
# gem 'ruby-units'

# パンくず
gem "crummy", "~> 1.7.2"
# meta, title tag
gem 'meta-tags'

group :development do
  #gem 'rmre'
  #gem 'metric_fu', :require => false
#  gem "erb2haml"
#  gem 'html2haml'
#  gem "rails-erd"
  #gem "foreigner", "~> 1.2"
  #gem "immigrant"
  gem 'awesome_print', :require => false
  gem 'sextant'
  gem 'better_errors'
  gem 'binding_of_caller'
  #gem 'meta_request'
  gem 'rack-mini-profiler', :require => false
  gem 'bullet'
#  gem 'railroady'
  #gem 'pry-rails', :require => false
  #gem 'pry-remote', :require => false
  #gem 'pry-debugger', :require => false
  #gem 'pry-stack_explorer', :require => false
  #gem 'pry-doc', :require => false
  gem 'thin', :require => false
  gem 'foreman', :require => false
  #gem 'zeus', :require => false
  gem 'selenium-webdriver'
  gem 'yard'
  #gem 'annotate', :require => false
  gem 'guard'
  #gem 'guard-sass'
  gem 'guard-ctags-bundler'
  #gem 'guard-coffeescript'
  #gem 'guard-jammit'
  gem 'guard-livereload'
  gem 'guard-bundler', require: false
end

group :test do
  gem 'fuubar'
  gem 'rspec'
  gem 'capybara'
  gem 'poltergeist'
  gem 'simplecov', '>=0.3.8', :require => false
  gem "launchy", "~> 2.3.0"
  gem 'database_cleaner'
end

group :development, :test do
  gem 'byebug'
  gem 'pry-byebug'
  gem 'speed_gun', :require => false
  gem 'rspec-rails'
  gem 'colored'
  gem 'quiet_assets'
  gem 'spork', :require => false
  gem 'guard-rails', :require => false
  gem 'growl', :require => false
  gem 'rails3-generators'
end

# Separating custom Gemfile per developer
# local_gemfile = File.dirname(__FILE__) + "/Gemfile.local.rb"
# if File.file?(local_gemfile)
#   self.instance_eval(Bundler.read_file(local_gemfile))
# end

# Peformance Monitoring Service 'NewRelic'
# Recommendation: Place the New Relic gem as low in the list as possible,  allowing the frameworks above it to be instrumented when the gem initializes:
# https://newrelic.com/docs/ruby/ruby-agent-installation
gem 'newrelic_rpm', :require => false
gem 'whenever', :require => false

#coore_on_railsより先に読み込みが必要
gem 'ckeditor', github: 'galetahub/ckeditor'

# http://bundler.io/v1.3/git.html
# bundle config local.coore_on_rails ~/work/rails_projects/coore_on_rails
#gem 'coore_on_rails', :git => "ssh://potvalley@potvalley.s-rep.net:11022/home/potvalley/git/coore_on_rails.git", :branch => "develop"
#gem 'coore_on_rails', :git => "ssh://git.s-rep.net/home/bitnami/git_repos/coore_on_rails.git", :branch => "i18n_en"
gem 'devise', '~> 2.2.3'
gem 'paper_trail', '~> 4.0.0.beta2'
# viewを使っていたりmigrationファイル内でrailsのコードを実行していたり、migration, rollbackがうまくいかないので削除
#gem 'activeadmin-selleo-cms'
gem 'i18n-js'
gem "mini_magick"
gem 'friendly_id'
#gem "resque", "~> 2.0.0.pre.1", github: "resque/resque"
gem "resque",  :git => "git://github.com/resque/resque.git", :branch => "1-x-stable", :require => 'resque/server'
gem 'resque-status'
gem 'god'
#gem 'guard'
#gem 'guard-sprockets'
#gem 'guard-rake'
gem 'best_in_place'
gem 'cocoon'
gem 'jquery-gmap3-rails'
gem 'andand'
gem 'rubyzip'
gem 'acts-as-taggable-on'
gem 'grouped_validations'
gem 'rack-ssl-enforcer'
gem 'jquery-tokeninput-rails'
gem "factory_girl_rails", "~> 4.0", :require => false

# View Components(for side-bar)
#gem 'cells'

group :development, :profile do
  gem 'ruby-prof'
end
gem 'strong_parameters'
gem 'public_activity'
gem 'aws-sdk', "~> 1.0"
gem 'amoeba', :git => "git://github.com/rocksolidwebdesign/amoeba.git"
gem 'jbuilder'
gem 'addressable'
gem 'metafy'
gem 'gretel'
gem 'turnout'
gem 'silencer'
gem "activerecord-tableless", "~> 1.0"
gem "paranoia", "~> 1.0"
gem "anemone"
gem "webrick"
gem 'redmon'
#gem 'capistrano-notifier'

gem 'sitemap_generator'
gem 'exception_notification-rake', '~> 0.0.6'
gem 'exception_notification'
gem "resque_exception_notification"
gem "lograge"
gem 'liquid-validator'
gem 'sendgrid-ruby'
gem 'chronic'
gem 'http_accept_language'
#gem 'globalize', '~> 3.1.0'
gem 'globalize', :git => 'https://github.com/globalize/globalize', :branch => '3-1-stable'
gem 'globalize-accessors'
gem 'redis-rails'
gem 'yen'
